# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_r2typ_wrappers", use_symbols = TRUE, package_name = "r2typ")

#' @usage NULL
#' @useDynLib r2typ, .registration = TRUE
NULL

#' Compile a `.typ` file to a sibling `.pdf` file and return the output path.
#' @export
typst_compile <- function(file) .Call(wrap__typst_compile, file)


# nolint end
